The flag 'directory' used in rule aggregate_transcript_analysis is only valid for outputs, not inputs.
The flag 'directory' used in rule output_combine_files is only valid for outputs, not inputs.
Building DAG of jobs...
Updating job output_combine_files.
Using shell: /bin/bash
Provided cores: 32
Rules claiming more threads will be scaled down.
Conda environments: ignored
Job counts:
	count	jobs
	1	all
	1	output_combine_files
	1	protein_coding_potential_analysis
	3
Select jobs to execute...

[Mon Apr  5 14:14:24 2021]
rule protein_coding_potential_analysis:
    input: Results/Genes/ADAR/ADAR_transcripts_filtered_analysis.txt, Results/Genes/ADAR/ADAR_transcripts_stats.txt, /project/owlmayerTemporary/Sid/ForOlga/Sequence/OlgaGenes.fa, /project/owlmayerTemporary/Sid/gencode/gencode.v32.primary_assembly.annotation.gtf
    output: Results/Genes/ADAR/ADAR_functional_analysis.pdf
    jobid: 4
    wildcards: gene=ADAR
    priority: 8
    resources: memory=16, time=1, tmpdir=0

[Mon Apr  5 14:14:38 2021]
Error in rule protein_coding_potential_analysis:
    jobid: 4
    output: Results/Genes/ADAR/ADAR_functional_analysis.pdf

RuleException:
CalledProcessError in line 653 of /home/annaldas/projects/IsoTV/Snakefile:
Command 'set -euo pipefail;  /home/annaldas/miniconda3/envs/isotv_update/bin/python3.7 /project/owlmayerTemporary/Sid/ForOlga/Sequence/.snakemake/scripts/tmp8h34vt1h.visualization.py' returned non-zero exit status 1.
  File "/home/annaldas/miniconda3/envs/isotv_update/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 2347, in run_wrapper
  File "/home/annaldas/projects/IsoTV/Snakefile", line 653, in __rule_protein_coding_potential_analysis
  File "/home/annaldas/miniconda3/envs/isotv_update/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 568, in _callback
  File "/home/annaldas/miniconda3/envs/isotv_update/lib/python3.7/concurrent/futures/thread.py", line 57, in run
  File "/home/annaldas/miniconda3/envs/isotv_update/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 554, in cached_or_run
  File "/home/annaldas/miniconda3/envs/isotv_update/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 2359, in run_wrapper
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /home/annaldas/projects/IsoTV/.snakemake/log/2021-04-05T141422.832435.snakemake.log
